export const MODEL_CREDITS = [
  {
    title: 'Asteroid 01',
    url: 'https://sketchfab.com/3d-models/asteroid-01-df95d3da67aa4c769ec81394e0b0ffef',
    author: 'exabyte',
    authorUrl: 'https://sketchfab.com/Oziry',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
  },
  {
    title: 'Callisto (moon)',
    url: 'https://sketchfab.com/3d-models/callisto-moon-459125fd885f4539ac423b6c3795a297',
    author: 'SebastianSosnowski',
    authorUrl: 'https://sketchfab.com/SebastianSosnowski',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
  },
  {
    title: 'ESA Rosetta comet',
    url: 'https://sketchfab.com/3d-models/esa-rosetta-comet-7748236dd9c64130a105acb53f69b7b5',
    author: 'Steren',
    authorUrl: 'https://sketchfab.com/steren',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
  },
  {
    title: 'Deimos',
    url: 'https://sketchfab.com/3d-models/deimos-db9c281d0a7b4452aaac26eb1d3738ad',
    author: 'uperesito',
    authorUrl: 'https://sketchfab.com/uperesito',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
  },
  {
    title: 'Earth',
    url: 'https://sketchfab.com/3d-models/earth-3684eb40fb7e42208089874e6286b9e9',
    author: 'denis_cliofas',
    authorUrl: 'https://sketchfab.com/denis_cliofas',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
  },
  {
    title: 'Ganymede (moon)',
    url: 'https://sketchfab.com/3d-models/ganymede-moon-7021e376ecb04b89b11fcbe017e48e8c',
    author: 'SebastianSosnowski',
    authorUrl: 'https://sketchfab.com/SebastianSosnowski',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
  },
  {
    title: 'Io v1.1',
    url: 'https://sketchfab.com/3d-models/io-v11-24eff42e8ac2429a945fddd722f4ef5c',
    author: 'uperesito',
    authorUrl: 'https://sketchfab.com/uperesito',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
  },
  {
    title: 'Realistic Jupiter',
    url: 'https://sketchfab.com/3d-models/realistic-jupiter-993ba62a539e4c308e9e3137df454ed6',
    author: 'Shady Tex',
    authorUrl: 'https://sketchfab.com/ShadyTex4u',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
  },
  {
    title: 'Mars',
    url: 'https://sketchfab.com/3d-models/mars-156a95dfec244e07a3ae423f579ffb05',
    author: 'ARCTIC  WOLVESâ„¢',
    authorUrl: 'https://sketchfab.com/arctic.wolves',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
  },
  {
    title: 'Mercury',
    url: 'https://sketchfab.com/3d-models/mercury-0a7a8958d49944f1aef057951daa8fd3',
    author: 'Anthony Yanez',
    authorUrl: 'https://sketchfab.com/paulyanez',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
  },
  {
    title: 'The Moon',
    url: 'https://sketchfab.com/3d-models/the-moon-9916fcec59f04b07b3e8d7f077dc3ded',
    author: 'SebastianSosnowski',
    authorUrl: 'https://sketchfab.com/SebastianSosnowski',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
  },
  {
    title: 'Neptune',
    url: 'https://sketchfab.com/3d-models/neptune-fe05e06a265d4a8f9285d34c933878ee',
    author: 'SebastianSosnowski',
    authorUrl: 'https://sketchfab.com/SebastianSosnowski',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
  },
  {
    title: 'Phobos_1_1000',
    url: 'https://sketchfab.com/3d-models/phobos-1-1000-a3acffcf706a4efead044ad623e94443',
    author: 'BescGuy',
    authorUrl: 'https://sketchfab.com/BescGuy',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
  },
  {
    title: 'Simple Satellite Low Poly Free',
    url: 'https://sketchfab.com/3d-models/simple-satellite-low-poly-free-f23b484cda664f1cb91b4f62ea5ef8bf',
    author: 'DjalalxJay',
    authorUrl: 'https://sketchfab.com/djalalxjay',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
  },
  {
    title: 'Saturno v1.1',
    url: 'https://sketchfab.com/3d-models/saturno-v11-5d546029721640a9ac332fb68b959e49',
    author: 'uperesito',
    authorUrl: 'https://sketchfab.com/uperesito',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
  },
  {
    title: 'Sun animated test',
    url: 'https://sketchfab.com/3d-models/sun-animated-test-8c3ebc78ec014042a61144f46c6f13fa',
    author: 'P3TroV',
    authorUrl: 'https://sketchfab.com/P3TroV',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
  },
  {
    title: 'Titan',
    url: 'https://sketchfab.com/3d-models/titan-56436d7ef2fb45b09c228344ee2bea9c',
    author: 'Danny.Gallegos',
    authorUrl: 'https://sketchfab.com/Danny.Gallegos',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
  },
  {
    title: 'Urano',
    url: 'https://sketchfab.com/3d-models/urano-b89a7d4c0f5147129b7fbac98ce70888',
    author: 'uperesito',
    authorUrl: 'https://sketchfab.com/uperesito',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
  },
  {
    title: 'Venus',
    url: 'https://sketchfab.com/3d-models/venus-36fe5066544f4f5e9eaf79dcb35a19c0',
    author: 'PatelDev',
    authorUrl: 'https://sketchfab.com/PatelDev',
    license: 'CC-BY-4.0',
    licenseUrl: 'http://creativecommons.org/licenses/by/4.0/',
  },
  {
    title: 'Tethys',
    url: 'https://science.nasa.gov/resource/tethys-3d-model/',
    author: 'NASA Visualization Technology Applications and Development (VTAD)',
    license: 'Public Domain (NASA source)',
    licenseUrl: 'https://www.nasa.gov/multimedia/guidelines/index.html',
  },
  {
    title: 'Dione',
    url: 'https://science.nasa.gov/resource/dione-3d-model/',
    author: 'NASA Visualization Technology Applications and Development (VTAD)',
    license: 'Public Domain (NASA source)',
    licenseUrl: 'https://www.nasa.gov/multimedia/guidelines/index.html',
  },
  {
    title: 'Enceladus',
    url: 'https://science.nasa.gov/resource/enceladus-3d-model/',
    author: 'NASA Visualization Technology Applications and Development (VTAD)',
    license: 'Public Domain (NASA source)',
    licenseUrl: 'https://www.nasa.gov/multimedia/guidelines/index.html',
  },
  {
    title: 'Europa',
    url: 'https://science.nasa.gov/resource/europa-3d-model/',
    author: 'NASA Visualization Technology Applications and Development (VTAD)',
    license: 'Public Domain (NASA source)',
    licenseUrl: 'https://www.nasa.gov/multimedia/guidelines/index.html',
  },
  {
    title: 'Iapetus',
    url: 'https://science.nasa.gov/resource/iapetus-3d-model/',
    author: 'NASA Visualization Technology Applications and Development (VTAD)',
    license: 'Public Domain (NASA source)',
    licenseUrl: 'https://www.nasa.gov/multimedia/guidelines/index.html',
  },
  {
    title: 'International Space Station',
    url: 'https://science.nasa.gov/resource/international-space-station-3d-model/',
    author: 'NASA Visualization Technology Applications and Development (VTAD)',
    license: 'Public Domain (NASA source)',
    licenseUrl: 'https://www.nasa.gov/multimedia/guidelines/index.html',
  },
  {
    title: 'Mimas',
    url: 'https://science.nasa.gov/resource/mimas-3d-model/',
    author: 'NASA Visualization Technology Applications and Development (VTAD)',
    license: 'Public Domain (NASA source)',
    licenseUrl: 'https://www.nasa.gov/multimedia/guidelines/index.html',
  },
  {
    title: 'Rhea',
    url: 'https://science.nasa.gov/resource/rhea-3d-model/',
    author: 'NASA Visualization Technology Applications and Development (VTAD)',
    license: 'Public Domain (NASA source)',
    licenseUrl: 'https://www.nasa.gov/multimedia/guidelines/index.html',
  },
];
